In [1]:
!wget -nc https://github.com/rapidsai/notebooks-extended/raw/master/utils/rapids-colab.sh
!bash rapids-colab.sh

import sys, os

sys.path.append('/usr/local/lib/python3.6/site-packages/')
os.environ['NUMBAPRO_NVVM'] = '/usr/local/cuda/nvvm/lib64/libnvvm.so'
os.environ['NUMBAPRO_LIBDEVICE'] = '/usr/local/cuda/nvvm/libdevice/'

--2020-01-22 07:17:46--  https://github.com/rapidsai/notebooks-extended/raw/master/utils/rapids-colab.sh
Resolving github.com (github.com)... 192.30.253.113
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/rapidsai/notebooks-contrib/raw/master/utils/rapids-colab.sh [following]
--2020-01-22 07:17:46--  https://github.com/rapidsai/notebooks-contrib/raw/master/utils/rapids-colab.sh
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rapidsai/notebooks-contrib/master/utils/rapids-colab.sh [following]
--2020-01-22 07:17:46--  https://raw.githubusercontent.com/rapidsai/notebooks-contrib/master/utils/rapids-colab.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubuserconten

# **cuDF**

In [ ]:
import os
import numpy as np
import pandas as pd
import math
np.random.seed(12)

In [4]:
print(f'Pandas Version: {pd.__version__}')

Pandas Version: 0.25.3


In [ ]:
df_pd = pd.DataFrame()

In [ ]:
df_pd['key'] = [0, 0, 2, 2, 3]

In [ ]:
df_pd['value'] = [float(i + 10) for i in range(5)]

In [8]:
df_pd

key  value
0    0   10.0
1    0   11.0
2    2   12.0
3    2   13.0
4    3   14.0

In [ ]:
sum_df_pd = df_pd['value'].sum()

In [10]:
sum_df_pd

60.0

From now on we work on cuDF 

In [ ]:
import cudf

In [12]:
print(f"cuDF Version: {cudf.__version__}")

cuDF Version: 0.10.0


In [ ]:
df_cu = cudf.DataFrame()

In [14]:
df_cu.shape

(0, 0)

In [ ]:
df_cu['key'] = [0, 0, 2, 2, 3]
df_cu['value'] = [float(i + 10) for i in range(5)]

In [16]:
df_cu

key  value
0    0   10.0
1    0   11.0
2    2   12.0
3    2   13.0
4    3   14.0

In [17]:
df_cu.index.values

array([0, 1, 2, 3, 4])

In [18]:
df_cu.columns

Index(['key', 'value'], dtype='object')

In [19]:
df_cu['value'].sum()

60.0

## Series & DataFrame

creating Series

In [20]:
s = cudf.Series(1, 2, 3, None, 4)
print(s)

2    1
Name: 3, dtype: int64


In [21]:
type(s)

cudf.core.series.Series

creating from direct assingment or from list, array, dictionary etc.

In [ ]:
dict_obj = {'a': list(range(20)),
            'b': reversed(list(range(20))),
            'c': list(range(20)),
            }

In [ ]:
df = cudf.DataFrame(dict_obj)

In [24]:
df.head(3)

a   b  c
0  0  19  0
1  1  18  1
2  2  17  2

creating from Pandas DataFrame

In [ ]:
pdf = pd.DataFrame({'a': [0, 1, 2, 3], 
                    'b': [0.1, 0.2, None, 0.3]})

In [26]:
pdf

a    b
0  0  0.1
1  1  0.2
2  2  NaN
3  3  0.3

In [ ]:
gdf = cudf.DataFrame.from_pandas(pdf)

In [28]:
gdf

a     b
0  0   0.1
1  1   0.2
2  2  null
3  3   0.3

## all analogous Pandas.DataFrame attributes & methods & index/slicing etc.

In [29]:
type(df)

cudf.core.dataframe.DataFrame

In [30]:
df

a   b   c
0    0  19   0
1    1  18   1
2    2  17   2
3    3  16   3
4    4  15   4
5    5  14   5
6    6  13   6
7    7  12   7
8    8  11   8
9    9  10   9
10  10   9  10
11  11   8  11
12  12   7  12
13  13   6  13
14  14   5  14
15  15   4  15
16  16   3  16
17  17   2  17
18  18   1  18
19  19   0  19

In [31]:
df.sort_values(by = 'b')

a   b   c
19  19   0  19
18  18   1  18
17  17   2  17
16  16   3  16
15  15   4  15
14  14   5  14
13  13   6  13
12  12   7  12
11  11   8  11
10  10   9  10
9    9  10   9
8    8  11   8
7    7  12   7
6    6  13   6
5    5  14   5
4    4  15   4
3    3  16   3
2    2  17   2
1    1  18   1
0    0  19   0

In [32]:
df.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [34]:
df['b'][:3]

0    19
1    18
2    17
Name: b, dtype: int64

In [35]:
df.loc[2:5, ['b', 'c', 'a']]

b  c  a
2  17  2  2
3  16  3  3
4  15  4  4
5  14  5  5

In [36]:
df.loc[[2, 4]]

a   b  c
2  2  17  2
4  4  15  4

In [37]:
df.iloc[[2, 3]]

a   b  c
2  2  17  2
3  3  16  3

In [38]:
df[3:5]

a   b  c
3  3  16  3
4  4  15  4

In [39]:
df.loc[[4, 9]]

a   b  c
4  4  15  4
9  9  10  9

In [40]:
df[df['b'] > 15]

a   b  c
0  0  19  0
1  1  18  1
2  2  17  2
3  3  16  3

In [41]:
df[df['b'] == 3]

a  b   c
16  16  3  16

In [42]:
df[(df['b'] == 3) | (df['b'] == 6)]

a  b   c
13  13  6  13
16  16  3  16

In [43]:
val = 3
df.query("b == @val")

a  b   c
16  16  3  16

In [44]:
df[df['b'] > (df['c'] + 6)]

a   b  c
0  0  19  0
1  1  18  1
2  2  17  2
3  3  16  3
4  4  15  4
5  5  14  5
6  6  13  6

## missings

In [45]:
gdf

a     b
0  0   0.1
1  1   0.2
2  2  null
3  3   0.3

In [48]:
gdf.fillna(999)

a      b
0  0    0.1
1  1    0.2
2  2  999.0
3  3    0.3

## Statistics

In [ ]:
s = cudf.Series(np.arange(10).astype(np.float64))

In [69]:
s

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [70]:
s.mean(), s.var()

(4.5, 9.166666666666668)

In [71]:
df.describe()

a         b         c
count  20.00000  20.00000  20.00000
mean    9.50000   9.50000   9.50000
std     5.91608   5.91608   5.91608
min     0.00000   0.00000   0.00000
25%     4.75000   4.75000   4.75000
50%     9.50000   9.50000   9.50000
75%    14.25000  14.25000  14.25000
max    19.00000  19.00000  19.00000

## applymap for Series, not working for DataFrame

In [72]:
s

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [ ]:
def add_10(num):
  return num + 10

In [74]:
s.applymap(add_10)

0    10.0
1    11.0
2    12.0
3    13.0
4    14.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64

## String Method

In [ ]:
s = cudf.Series(['A', 'B', 'C', 'Aaba', 'Baca', None, 'CABA', 'dog', 'cat'])

In [91]:
s

0       A
1       B
2       C
3    Aaba
4    Baca
5    None
6    CABA
7     dog
8     cat
dtype: object

In [92]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5    None
6    caba
7     dog
8     cat
dtype: object

In [94]:
s.str.title()

0       A
1       B
2       C
3    Aaba
4    Baca
5    None
6    Caba
7     Dog
8     Cat
dtype: object

## Concat

In [ ]:
s = cudf.Series([1, 2, 3, None, 5])

In [ ]:
s_double_vertical = cudf.concat([s, s])

In [99]:
s_double_vertical

0       1
1       2
2       3
3    null
4       5
0       1
1       2
2       3
3    null
4       5
dtype: int64

In [103]:
type(s_double_vertical)

cudf.core.series.Series

In [ ]:
s_double_horizontal = cudf.concat([s, s], axis =1)

In [102]:
s_double_horizontal

-1     0
0     1     1
1     2     2
2     3     3
3  null  null
4     5     5

In [104]:
type(s_double_horizontal)

cudf.core.dataframe.DataFrame

## Append

In [105]:
print(s.append(s))

0       1
1       2
2       3
3    null
4       5
0       1
1       2
2       3
3    null
4       5
dtype: int64


## Join

In [ ]:
df_a = cudf.DataFrame()
df_a['key'] = ['a', 'b', 'c', 'd', 'e']
df_a['vals_a'] = [float(i + 10) for i in range(5)]

df_b = cudf.DataFrame()
df_b['key'] = ['a', 'c', 'e']
df_b['vals_b'] = [float(i+100) for i in range(3)]

In [107]:
df_a

key  vals_a
0   a    10.0
1   b    11.0
2   c    12.0
3   d    13.0
4   e    14.0

In [108]:
df_b

key  vals_b
0   a   100.0
1   c   101.0
2   e   102.0

In [109]:
merged = df_a.merge(df_b, on=['key'], how='inner')
print(merged)

  key  vals_a  vals_b
0   a    10.0   100.0
1   c    12.0   101.0
2   e    14.0   102.0


In [110]:
merged_left = df_a.merge(df_b, on=['key'], how='left')
print(merged_left)

  key  vals_a vals_b
0   a    10.0  100.0
1   c    12.0  101.0
2   e    14.0  102.0
3   b    11.0   null
4   d    13.0   null


## Grouping

In [113]:
df.head(3)

a   b  c
0  0  19  0
1  1  18  1
2  2  17  2

In [112]:
len(df)

20

In [ ]:
df['agg_col1'] = [1 if i % 2 == 0 else 0 for i in range(len(df))]
df['agg_col2'] = [1 if i % 3 == 0 else 0 for i in range(len(df))]

In [116]:
df.head(3)

a   b  c  agg_col1  agg_col2
0  0  19  0         1         1
1  1  18  1         0         0
2  2  17  2         1         0

In [117]:
df.groupby('agg_col1').sum()

a    b    c  agg_col2
agg_col1                         
0         100   90  100         3
1          90  100   90         4

In [124]:
df.groupby('agg_col1').agg({'a': 'sum', 'b': 'mean', 'c': 'max'})

a     b   c
agg_col1               
0         100   9.0  19
1          90  10.0  18

In [125]:
df.groupby(['agg_col1', 'agg_col2']).agg({'a': 'mean', 'b': 'min'})

a  b
agg_col1 agg_col2              
0        0         10.428571  0
         1          9.000000  4
1        0          9.000000  3
         1          9.000000  1

## Time-Series

In [134]:
date_df = cudf.DataFrame()
date_df['date'] = pd.date_range('12/11/2019', periods=72, freq='D')
date_df['value'] = np.random.sample(len(date_df))
print(date_df.head())

        date     value
0 2019-12-11  0.863752
1 2019-12-12  0.013863
2 2019-12-13  0.074093
3 2019-12-14  0.375916
4 2019-12-15  0.249364


In [135]:
date_df.shape

(72, 2)

In [131]:
date_df['date'].dtype

dtype('<M8[ns]')

In [139]:
date_df['date'].dt.year.unique()

0    2019
1    2020
Name: date, dtype: int16

In [ ]:
search_date = pd.to_datetime('2019-12-15')

In [163]:
search_date

Timestamp('2019-12-15 00:00:00')

In [164]:
date_df.query('date < @search_date')

date     value
0 2019-12-11  0.863752
1 2019-12-12  0.013863
2 2019-12-13  0.074093
3 2019-12-14  0.375916

In [165]:
date_df.head(2)

date     value
0 2019-12-11  0.863752
1 2019-12-12  0.013863

In [ ]:
date_df['month'] = date_df['date'].dt.month

In [174]:
date_df.head(2)

date     value  minute  month
0 2019-12-11  0.863752       0     12
1 2019-12-12  0.013863       0     12

In [175]:
date_df.tail(2)

date     value  minute  month
70 2020-02-19  0.480925       0      2
71 2020-02-20  0.756821       0      2

## Converting cuDF.DataFrame to Pandas.DataFrame

In [176]:
type(date_df)

cudf.core.dataframe.DataFrame

In [ ]:
date_pdf = date_df.head().to_pandas()

In [178]:
date_pdf

date     value  minute  month
0 2019-12-11  0.863752       0     12
1 2019-12-12  0.013863       0     12
2 2019-12-13  0.074093       0     12
3 2019-12-14  0.375916       0     12
4 2019-12-15  0.249364       0     12

## Converting cuDF.DataFrame to np.ndarray | a cuDF.Series to np.ndarray

In [ ]:
# date_arr = date_df.as_matrix()                       # some issue due to datetime field

In [184]:
df.head(3)

a   b  c  agg_col1  agg_col2
0  0  19  0         1         1
1  1  18  1         0         0
2  2  17  2         1         0

In [ ]:
df_arr = df.as_matrix()

In [186]:
df_arr

array([[ 0, 19,  0,  1,  1],
       [ 1, 18,  1,  0,  0],
       [ 2, 17,  2,  1,  0],
       [ 3, 16,  3,  0,  1],
       [ 4, 15,  4,  1,  0],
       [ 5, 14,  5,  0,  0],
       [ 6, 13,  6,  1,  1],
       [ 7, 12,  7,  0,  0],
       [ 8, 11,  8,  1,  0],
       [ 9, 10,  9,  0,  1],
       [10,  9, 10,  1,  0],
       [11,  8, 11,  0,  0],
       [12,  7, 12,  1,  1],
       [13,  6, 13,  0,  0],
       [14,  5, 14,  1,  0],
       [15,  4, 15,  0,  1],
       [16,  3, 16,  1,  0],
       [17,  2, 17,  0,  0],
       [18,  1, 18,  1,  1],
       [19,  0, 19,  0,  0]])

In [187]:
date_df.head(3)

date     value  minute  month
0 2019-12-11  0.863752       0     12
1 2019-12-12  0.013863       0     12
2 2019-12-13  0.074093       0     12

In [ ]:
month_arr = date_df['month'].to_array()

In [189]:
month_arr

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2], dtype=int16)

## In & Out

In [ ]:
df.to_pandas().to_csv('foo.csv', index=False)

read back

In [ ]:
csv_back = cudf.read_csv('foo.csv')

In [195]:
csv_back.head(2)

a   b  c  agg_col1  agg_col2
0  0  19  0         1         1
1  1  18  1         0         0

In [196]:
type(csv_back)

cudf.core.dataframe.DataFrame

## Performance of cuDA vs Pandas

In [ ]:
a = np.random.rand(10_000_000)

In [ ]:
pdf = pd.DataFrame()
cdf = cudf.DataFrame()

In [200]:
%time pdf['a'] = a
%time cdf['a'] = a

CPU times: user 545 ms, sys: 225 ms, total: 769 ms
Wall time: 775 ms
CPU times: user 21 ms, sys: 0 ns, total: 21 ms
Wall time: 21.1 ms


In [201]:
%%timeit
pdf['a'].sum()

10 loops, best of 3: 48.4 ms per loop


In [202]:
%%timeit
cdf['a'].sum()

1000 loops, best of 3: 544 µs per loop


## A Realistic Example

To get a more realistic sense of how powerful cuDF and GPUs can be, let's imagine you had a fleet of sensors that collect data every millisecond. These sensors could be measuring pressure, temperature, or something else entirely.

Let's imagine we want to analyze one day's worth of sensor data. We'll assign random values for the sensor `value` to use for this example. We'll start by creating the data, and generating some datetime related features like we learned about in the aboves

You can start a cell with `%%time` to time the cell, or with `%%timeit`, which runs the cell multiple times and gives an average. `%%timeit` gives a more accurate benchmark but takes longer to run.

In [205]:
%%time

# creating data
date_df = pd.DataFrame()
date_df['date'] = pd.date_range(start='2020-01-23', end='2020-01-24', freq='ms')
date_df['value'] = np.random.sample(len(date_df))

date_df['hour'] = date_df.date.dt.hour
date_df['minute'] = date_df.date.dt.minute

print(date_df.shape)

(86400001, 4)
CPU times: user 20.1 s, sys: 1.89 s, total: 22 s
Wall time: 22 s


In [206]:
date_df.head(3)

date     value  hour  minute
0 2020-01-23 00:00:00.000  0.387646     0       0
1 2020-01-23 00:00:00.001  0.200427     0       0
2 2020-01-23 00:00:00.002  0.530535     0       0

In [207]:
%time 
results = date_df.groupby(['hour', 'minute']).agg({'value':'max'})
results.head()

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs


value
hour minute          
0    0       0.999985
     1       0.999990
     2       0.999964
     3       0.999994
     4       0.999982

now using gpu & cuDF

In [210]:
%%time

date_cdf = cudf.DataFrame()
date_cdf['date'] = pd.date_range(start='2019-07-05', end='2019-07-06', freq='ms')
date_cdf['value'] = np.random.sample(len(date_cdf))

date_cdf['hour'] = date_cdf.date.dt.hour
date_cdf['minute'] = date_cdf.date.dt.minute
date_cdf['second'] = date_cdf.date.dt.second

print(date_cdf.shape)

(86400001, 5)
CPU times: user 1.58 s, sys: 38.8 ms, total: 1.61 s
Wall time: 1.62 s


In [211]:
print(date_cdf.head())

                     date     value  hour  minute  second
0 2019-07-05 00:00:00.000  0.144546     0       0       0
1 2019-07-05 00:00:00.001  0.725456     0       0       0
2 2019-07-05 00:00:00.002  0.372234     0       0       0
3 2019-07-05 00:00:00.003  0.056032     0       0       0
4 2019-07-05 00:00:00.004  0.619107     0       0       0


In [212]:
%time 
results_cdf = date_cdf.groupby(['hour', 'minute', 'second']).agg({'value':'max'})
results_cdf.head()

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.29 µs


value
hour minute second          
0    0      0       0.998936
            1       0.996985
            2       0.998953
            3       0.998449
            4       0.999713